### ISSUE TITLE
Acitivity inconsistency, displays your user when you remove/add someone else from event

### ISSUE THREAD

**Issue by klstilling** [connors511/dinto-issues#60]
When you add or remove someone else from an event, it creates an activity with the contents: "<your name> has joined/left" instead of "<target name> has joined/left".
Maybe the acitivity could say something about who added who in the case where one person adds another person to an event.

Also, there is inconsistency in the use of list items or no list items for the acitivity text in the "<name> changed...", I vote for no list items as text format. An example of this is supplied here:

Adam 1 week ago
+ Changed date from 2017-03-29 to 2017-04-05

Adam 1 week ago
Changed the status from cancelled to open

**Comment by jonaslb** [comment]
*Some* events seem to have a problem showing any "xxx joined" activity at all.

**Comment by connors511** [comment]
@klstilling @jonaslb I've located the issue regarding activity on join/leave, which is two fold.
First part is when an organizer is editing a participants status on their behalf -- the data was just parsed incorrectly by the front end.
Some participants might not have the "joined" event at all. Under some circumstances, the event wasn't fired due to how the participants stati (going / not going / unanswered) is tracked.
These two issues has been fixed and pending a release.

Regarding list vs non-list for activity, all changes to an event triggers a history event which is being rendered as a text line like `changed status`.
The only exception is when the entire event is edited -- this will trigger a combined activity of all the event attributes that has been changed, which will be rendered by the front end as a list of `changed FIELD from OLD to NEW`
@klstilling if this should be consistent with the rest of the activity items, how do you suggest the message look if multiple fields is changed at the same time?
Something like `Changed title from Hello to World, time from 08:00 to 19:00 and date from 1st april to 2nd april`?

**Comment by klstilling** [comment]
@connors511 I think that the list style is preferable if multiple changes are grouped together in a single activity, but if only there is only a single change it should just look like the rest of the acitvities (no list style). I think that this is mostly a matter of taste, I just think that it looks better. I would really prefer the list style over the comma separated string style!
